### ISSUE TITLE
Cek dependensi dan koneksi internet

### ISSUE THREAD

**Issue by kahidna** [hendramanu/InfoCovid#1]
aplikasi sudah keren. akan lebih keren kalo ditambah fungsi cek koneksi internet dan fungsi cek dependensi. cek koneksi internet menjadi krusial karena jika tidak terhubung ke internet data  yang tampil tentang statistik covid menjadi tidak muncul.
![image](https://user-images.githubusercontent.com/4997301/108998541-a1395c00-76d3-11eb-856b-8ae8a09238ec.png)

selain itu dalam aplikasi butuh package `pv`. jadi bisa cek dulu apakah package pv sudah terinstall atau belum pada sistem. meski tidak krusial tapi akan menyempurnakan aplikasi itu sendiri
![image](https://user-images.githubusercontent.com/4997301/108998503-941c6d00-76d3-11eb-95be-5a9bacac9181.png)

cheers.

**Comment by hendramanu** [comment]
Siap, terima kasih feedbacknya.

**Comment by hendramanu** [comment]
Sip, diperbaiki. Sekali lagi terima kasih atas feedback dan ketelitiannya 😄
